DROP TABLE IF EXISTS T_STORE_HAS_PRODUCT;
DROP TABLE IF EXISTS T_STORE;
DROP TABLE IF EXISTS T_PRODUCT;

CREATE TABLE T_STORE (
	ID INTEGER,
	CODE VARCHAR(50) NOT NULL,
	XYZ INTEGER NOT NULL,
	NAME VARCHAR(50) NOT NULL
);
ALTER TABLE T_STORE ADD CONSTRAINT T_STORE_ID PRIMARY KEY (ID);

CREATE TABLE T_PRODUCT (
	ID INTEGER,
	CODE VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL
);
ALTER TABLE T_PRODUCT ADD CONSTRAINT T_PRODUCT_ID PRIMARY KEY (ID);

CREATE TABLE T_STORE_HAS_PRODUCT (
	STORE INTEGER NOT NULL,
	PRODUCT INTEGER NOT NULL,
	PRICE	FLOAT NOT NULL
);
ALTER TABLE T_STORE_HAS_PRODUCT ADD CONSTRAINT T_STORE_HAS_PRODUCT_STORE_ID FOREIGN KEY (STORE) REFERENCES T_STORE(ID);
ALTER TABLE T_STORE_HAS_PRODUCT ADD CONSTRAINT T_STORE_HAS_PRODUCT_PRODUCT_ID  FOREIGN KEY (PRODUCT) REFERENCES T_PRODUCT(ID)
ALTER TABLE T_STORE_HAS_PRODUCT ADD CONSTRAINT T_STORE_HAS_PRODUCT_PK PRIMARY KEY (STORE,PRODUCT);

