/**
 *
 * My private copyright 2
 *
 */
package fr.xebia.reveng.model.store;

// Generated test Mar 12, 2012 10:52:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import fr.xebia.reveng.model.common.IPojoWithCode;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "T_STORE", schema = "PUBLIC", catalog = "PUBLIC")
public class Store implements IPojoWithCode, java.io.Serializable {

    private int id;
    private String code;
    private int nbRayons;
    private String name;
    private Set<StoreHasProduct> storeHasProducts = new HashSet<StoreHasProduct>(
	    0);

    public Store() {
    }

    public Store(int id, String code, int nbRayons, String name) {
	this.id = id;
	this.code = code;
	this.nbRayons = nbRayons;
	this.name = name;
    }

    public Store(int id, String code, int nbRayons, String name,
	    Set<StoreHasProduct> storeHasProducts) {
	this.id = id;
	this.code = code;
	this.nbRayons = nbRayons;
	this.name = name;
	this.storeHasProducts = storeHasProducts;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @Column(name = "CODE", nullable = false, length = 50)
    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    @Column(name = "XYZ", nullable = false)
    public int getNbRayons() {
	return this.nbRayons;
    }

    public void setNbRayons(int nbRayons) {
	this.nbRayons = nbRayons;
    }

    @Column(name = "NAME", nullable = false, length = 50)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
    public Set<StoreHasProduct> getStoreHasProducts() {
	return this.storeHasProducts;
    }

    public void setStoreHasProducts(Set<StoreHasProduct> storeHasProducts) {
	this.storeHasProducts = storeHasProducts;
    }

}
