/**
 *
 * My private copyright 2
 *
 */
package fr.xebia.reveng.model.store;

// Generated test Mar 12, 2012 10:52:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.xebia.reveng.model.Product;

/**
 * StoreHasProduct generated by hbm2java
 */
@Entity
@Table(name = "T_STORE_HAS_PRODUCT", schema = "PUBLIC", catalog = "PUBLIC")
public class StoreHasProduct implements java.io.Serializable {

    private StoreHasProductId id;
    private Store store;
    private Product product;
    private double price;

    public StoreHasProduct() {
    }

    public StoreHasProduct(StoreHasProductId id, Store store, Product product,
	    double price) {
	this.id = id;
	this.store = store;
	this.product = product;
	this.price = price;
    }

    @EmbeddedId
    @AttributeOverrides({
	    @AttributeOverride(name = "store", column = @Column(name = "STORE", nullable = false)),
	    @AttributeOverride(name = "product", column = @Column(name = "PRODUCT", nullable = false)) })
    public StoreHasProductId getId() {
	return this.id;
    }

    public void setId(StoreHasProductId id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STORE", nullable = false, insertable = false, updatable = false)
    public Store getStore() {
	return this.store;
    }

    public void setStore(Store store) {
	this.store = store;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRODUCT", nullable = false, insertable = false, updatable = false)
    public Product getProduct() {
	return this.product;
    }

    public void setProduct(Product product) {
	this.product = product;
    }

    @Column(name = "PRICE", nullable = false, precision = 64, scale = 0)
    public double getPrice() {
	return this.price;
    }

    public void setPrice(double price) {
	this.price = price;
    }

}
